import type { Metadata } from "next";
import LegalPage from "@/components/legal/LegalPage";

export const metadata: Metadata = { title: "Terms of Service — ZeroKore" };

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="September 2026">
      <section>
        <h2 className="mb-2 text-base font-semibold text-white">1. Acceptance</h2>
        <p>
          By creating an account or using ZeroKore (&quot;the Service&quot;), you agree
          to these Terms of Service. If you do not agree, do not use the
          Service. These terms apply to every visitor, registered user, and
          administrator of the Service.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-white">2. The Service</h2>
        <p>
          ZeroKore provides a browser-based AI workspace: conversations with AI
          agents, artifact generation, long-term memory, skills, and usage
          tracking. Features that depend on third parties — AI model providers,
          the database, GitHub connectivity, web search — are provided
          &quot;as available&quot; and may be temporarily or permanently unavailable.
          The Service indicates truthfully when a capability is not configured
          rather than simulating results.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-white">3. Your account</h2>
        <p>
          You are responsible for the activity that happens under your account,
          including keeping your password confidential. One human per account.
          You must be at least 13 years old (or the minimum digital-consent age
          in your country) to create an account. You may delete your account at
          any time by contacting the operator.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-white">4. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Use the Service to generate malware, harassment, or unlawful content.</li>
          <li>Attempt to access other users&apos; data, bypass authentication, or exploit the Service.</li>
          <li>Resell, scrape, or overload the Service or its upstream providers.</li>
          <li>Circumvent usage limits or billing controls.</li>
        </ul>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-white">5. AI-generated content</h2>
        <p>
          Responses and artifacts are generated by AI models and may be
          inaccurate or incomplete. You are responsible for reviewing anything
          you rely on or publish. You own the inputs you submit and, to the
          extent permitted by law, the outputs generated for you.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-white">6. Usage limits</h2>
        <p>
          The Service applies per-account daily request limits to keep the
          platform available for everyone. Limits, pricing, and model
          availability may change with notice on the dashboard.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-white">7. Termination</h2>
        <p>
          The operator may suspend or terminate accounts that violate these
          terms, abuse upstream providers, or create legal risk. You may stop
          using the Service at any time; your conversations and memory are
          deleted on account deletion.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-white">8. Disclaimer &amp; liability</h2>
        <p>
          The Service is provided &quot;as is&quot; without warranties of any kind. To
          the maximum extent permitted by law, the operator is not liable for
          indirect, incidental, or consequential damages arising from your use
          of the Service.
        </p>
      </section>

      <section>
        <h2 className="mb-2 text-base font-semibold text-white">9. Changes</h2>
        <p>
          These terms may be updated; material changes will be announced on the
          Service. Continuing to use ZeroKore after a change constitutes
          acceptance.
        </p>
      </section>
    </LegalPage>
  );
}
