-- Admin credentials table (Supabase side)
-- Stores username + password hash for the /kore/admin panel.
-- Set credentials once via the /api/kore/admin/setup API (or directly here).
-- No env vars needed — the app reads from this table.

create table if not exists admin_credentials (
  id          bigint generated by default as identity primary key,
  username    text not null unique,
  password_hash text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table admin_credentials enable row level security;

-- Only the service role (server-side) should read/write this table.
-- In practice, the app uses the service role key for these calls.
grant select on table admin_credentials to service_role;
grant insert on table admin_credentials to service_role;
grant update on table admin_credentials to service_role;
grant delete on table admin_credentials to service_role;